namespace Gate.IO.Api.Spot;

/// <summary>
/// Spot Order Request
/// </summary>
public record GateSpotOrderRequest
{
    /// <summary>
    /// User defined information. If not empty, must follow the rules below:  
    /// 1. prefixed with t-
    /// 2. no longer than 28 bytes without t- prefix
    /// 3. can only include 0-9, A-Z, a-z, underscore(_), hyphen(-) or dot(.)
    /// </summary>
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    public string ClientOrderId { get; set; }

    /// <summary>
    /// Currency pair
    /// </summary>
    [JsonProperty("currency_pair")]
    public string Symbol { get; set; }

    /// <summary>
    /// Actual quote currency for a unified market, selected from the market's TradeQuotes.
    /// Omit to retain the server's default. The wrapper never substitutes the currency pair's quote.
    /// </summary>
    [JsonProperty("trade_quote", NullValueHandling = NullValueHandling.Ignore)]
    public string TradeQuote { get; set; }

    /// <summary>
    /// Order Type
    /// </summary>
    [JsonProperty("type"), JsonConverter(typeof(MapConverter))]
    public GateSpotOrderType Type { get; set; }

    /// <summary>
    /// Account type: spot, margin or unified. CrossMargin is retained for compatibility.
    /// </summary>
    [JsonProperty("account"), JsonConverter(typeof(MapConverter))]
    public GateSpotAccountType Account { get; set; }

    /// <summary>
    /// Order side
    /// </summary>
    [JsonProperty("side"), JsonConverter(typeof(MapConverter))]
    public GateSpotOrderSide Side { get; set; }

    /// <summary>
    /// Base-currency quantity for limit orders and market sells. For market buys, the amount is in the actual quote currency (TradeQuote when specified).
    /// </summary>
    [JsonProperty("amount"), JsonConverter(typeof(GateDecimalStringConverter))]
    public decimal Amount { get; set; }

    /// <summary>
    /// Price can't be empty when "type" is limit
    /// </summary>
    [JsonProperty("price", NullValueHandling = NullValueHandling.Ignore), JsonConverter(typeof(GateDecimalStringConverter))]
    public decimal? Price { get; set; }

    /// <summary>
    /// Time in force  - gtc: GoodTillCancelled - ioc: ImmediateOrCancelled, taker only - poc: PendingOrCancelled, makes a post-only order that always enjoys a maker fee - fok: FillOrKill, fill either completely or none Only &#x60;ioc&#x60; and &#x60;fok&#x60; are supported when &#x60;type&#x60;&#x3D;&#x60;market&#x60;
    /// </summary>
    [JsonProperty("time_in_force", NullValueHandling = NullValueHandling.Ignore), JsonConverter(typeof(MapConverter))]
    public GateSpotTimeInForce? TimeInForce { get; set; }

    /// <summary>
    /// Amount to display for the iceberg order. Null or 0 for normal orders. Hiding the entire amount is not supported.
    /// </summary>
    [JsonProperty("iceberg", NullValueHandling = NullValueHandling.Ignore), JsonConverter(typeof(GateDecimalStringConverter))]
    public decimal? Iceberg { get; set; }

    /// <summary>
    /// Maximum price deviation for market orders
    /// </summary>
    [JsonProperty("slippage", NullValueHandling = NullValueHandling.Ignore), JsonConverter(typeof(GateDecimalStringConverter))]
    public decimal? Slippage { get; set; }

    /// <summary>
    /// Used in margin or cross margin trading to allow automatic loan of insufficient amount if balance is not enough.
    /// </summary>
    [JsonProperty("auto_borrow", NullValueHandling = NullValueHandling.Ignore)]
    public bool? AutoBorrow { get; set; }

    /// <summary>
    /// Enable or disable automatic repayment for an automatic borrow loan generated by a cross-margin order. Auto borrow and auto repay can both be enabled for the same order.
    /// </summary>
    [JsonProperty("auto_repay", NullValueHandling = NullValueHandling.Ignore)]
    public bool? AutoRepay { get; set; }

    /// <summary>
    /// Self-Trading Prevention Action. Users can use this field to set self-trade prevetion strategies
    /// </summary>
    [JsonProperty("stp_act", NullValueHandling = NullValueHandling.Ignore), JsonConverter(typeof(MapConverter))]
    public GateSpotSelfTradeAction? SelfTradeAction { get; set; }

    /// <summary>
    /// Processing Mode
    /// </summary>
    [JsonProperty("action_mode", NullValueHandling = NullValueHandling.Ignore), JsonConverter(typeof(MapConverter))]
    public GateSpotActionMode? ActionMode { get; set; }

    /// <summary>
    /// Take-profit settings for a limit order. For buy orders, the trigger price must be greater than the order price; for sell orders, it must be lower.
    /// </summary>
    [JsonProperty("stop_profit", NullValueHandling = NullValueHandling.Ignore)]
    public GateSpotOrderTpsl StopProfit { get; set; }

    /// <summary>
    /// Stop-loss settings for a limit order. For buy orders, the trigger price must be lower than the order price; for sell orders, it must be greater.
    /// </summary>
    [JsonProperty("stop_loss", NullValueHandling = NullValueHandling.Ignore)]
    public GateSpotOrderTpsl StopLoss { get; set; }
}
